# Site settings
title: The UI Dev
description: Playing catch up with the latest in the field of UI
baseurl: "" # the subpath of your site
url: "https://theuidev.github.io" # the base hostname & protocol for your site
comments: true

# User settings
username: The UI Dev
user_description: Sr. UI Developer @ Macy's Inc.
user_title: Shreerang Patwardhan
email: patwardhan.shreerang@gmail.com
twitter_username: shreerangp
github_username: Shreerang
gplus_username: +ShreerangPatwardhan
disqus_username: https-theuidev-github-io

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: ES6 101 Series
    url: /series
  - title: jQuery Mobile Series
    url: /series
  - title: Google Maps Javascript API Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
